<h2>1.MENTIONS LEGALES</h2>
<p>
Le site www.Netframe.fr (le Site) est édité par Illisite, société à responsabilité limitée au capital de 27.754 euros, immatriculé au RCS de Versailles sous le numéro 433.508.439, dont le siège social est situé 43 bvd Vauban à Guyancourt (78280), France. Vous pouvez contacter Netframe par email <a href="mailto:contact@Netframe.fr">contact@Netframe.fr</a> et par téléphone au +(33).1.46.57.02.48.<br />
Le Directeur de publication du Site est Monsieur Alexandre Afchain, Directeur associé de illisite<br />
Le Site est hébergé par OVH SAS, situé 2 rue Kellermann à Roubaix (59100), téléphone +(33).09.72.10.10.07.
</p>
<h2>2. CONDITIONS GENERALES D'UTILISATION DU SITE ET DES SERVICES (CGU)</h2>
<h3>2.1.	Description du Site et des Services</h3>
<p>
Netframe est une plateforme de réseau social d'entreprise.
</p>
<h3>2.2. Acceptation des CGU</h3>
<p>
Les présentes CGU entrent en vigueur à la date de leur mise en ligne. La consultation, l'utilisation du Site et/ou des différents Services offerts par le Site impliquent l'acceptation sans réserve des présentes CGU et le respect des dispositions légales et réglementaires en vigueur.<br />
Les CGU sont par conséquent opposables à tout internaute accédant au Site, qu'il soit simple utilisateur et/ou Membre (tel que ce terme est défini à l'Article 2.4 des présentes) (ensemble, les Utilisateurs). Il appartient donc à l'Utilisateur de prendre connaissance des présentes CGU dès sa première connexion au Site et de les consulter régulièrement.
</p>
<h3>2.3.	Accès au Site</h3>
<p>
L'Utilisateur reconnaît disposer de la compétence et des moyens techniques requis pour accéder et consulter le Site. Il s'assure également que toute personne accédant au Site par l'intermédiaire de sa connexion Internet a pris connaissance des présentes CGU et les a acceptées.<br />
L'Utilisateur reconnaît que les caractéristiques et les contraintes d'Internet ne permettent pas de garantir la sécurité, la disponibilité et l'intégrité des transmissions de données. L'Utilisateur s'engage à prendre toutes mesures appropriées de nature à protéger ses propres données, son système d'information et/ou logiciels de toute intrusion ou contamination par d'éventuels virus. L'Utilisateur s'interdit d'accéder ou de se maintenir frauduleusement dans le Site, d'entraver ou d'altérer le fonctionnement de celui-ci notamment en y introduisant des chevaux de Troie, bombes logiques, vers informatiques ou tout autre virus ou programme malveillant ou susceptible de causer un quelconque dommage au Site.
</p>
<h3>2.4.	Modes d'utilisation des Services – fonctionnalités</h3>
<p>
Le Site et les Services sont librement disponibles à la lecture simple par les Utilisateurs (utilisation en mode passif). Lorsque l'Utilisateur souhaite bénéficier des Services de manière active (par exemple, en postant tout message à l'intention d'un groupe Netframe, en publiant en son nom des informations sur d'autres talents (Talents Angel), en participant aux divers forums de discussion ou en contribuant aux échanges sur Netframe de toute autre manière), il doit préalablement (i) reconnaître de manière expresse avoir lu et accepter les présentes CGU en cochant la case prévue à cet effet sur le formulaire d'inscription, puis (ii) s'inscrire sur le Site. Pour les besoins des présentes CGU, l'Utilisateur bénéficiant des Services ou y contribuant de manière active est alors qualifié de Membre de la communauté Netframe.<br />
Les Services (en mode actif) sont par conséquent accessibles à tout Membre après saisie de son adresse email et d'un mot de passe qu'il aura lui-même déterminés. Lors de cette inscription, le Membre s'engage à communiquer des informations exactes portant sur son identité, ses coordonnées, ses aptitudes et talents particuliers, projets. Il s'engage également à procéder à la mise à jour de ses informations régulièrement.<br />
Les identifiants sont strictement personnels et confidentiels et ne peuvent être communiqués à des tiers. Afin d'assurer la sécurité du Site, les mots de passe des Membres devront être constitués d'au moins huit (8) caractères. Netframe invite le Membre à modifier fréquemment son mot de passe. Le Membre reconnaît être seul responsable de l'utilisation de ses identifiants par des tiers ou des actes et déclarations faites par l'intermédiaire du Site en utilisant ses identifiants. Le Membre s'engage à informer Netframe sans délai en cas d'utilisation non autorisée de ses identifiants.<br />
Le Membre peut, à tout moment, se désinscrire en suivant les indications figurant sur le Site. Il recevra alors une confirmation de cette désinscription de son compte par email à l'adresse qu'il a renseignée lors de l'inscription. Sous réserve d'une information préalablement diffusée par mail, Netframe est également fondé à fermer un compte de Membre et mettre fin à la participation d'un Membre à un groupe Netframe ou à un forum de discussion, pour quelque raison que ce soit et à tout instant.<br />
Le Membre s'oblige à n'avoir qu'un seul compte et à ne laisser personne l'utiliser à sa place. Il s'interdit d'utiliser le compte de quelqu'un d'autre ou de déclarer sur le Site une identité usurpée ou factice.<br />
Le Membre s'interdit également de diffuser sur le Site tout contenu contraire à la loi, à l'ordre public ou aux droits de Netframe, de ses partenaires, des autres Utilisateurs ou de tous autres tiers. En particulier, le Membre s'engage à (i) respecter les droits de propriété intellectuelle afférents aux contenus fournis par Netframe et par les autres Membres, ainsi que les droits de propriété intellectuelle des tiers et partenaires de Netframe ; (ii) ne pas perturber le fonctionnement des Services en multipliant de manière déraisonnable les diffusions de contenu dont la forme ou le volume aurait pour effet de réduire, désorganiser ou altérer l'utilisation normale du Site et des Services ; (iii) ne pas publier de contenu à caractère diffamatoire, injurieux, obscène, offensant, incitant à la violence ou xénophobe, prosélyte ; (iv) ne pas collecter d'informations sur des tiers ou d'autres Utilisateurs aux fins d'envoi de prospection commerciale.<br />
De manière générale, il est rappelé que Netframe ne saurait en aucun cas être tenu responsable de toute situation ou dommage qui pourrait survenir au cours ou à l'issue de contacts noués entre les Utilisateurs à travers le Site ou par le biais des Services.
</p>
<h3>2.5.	Propriété intellectuelle</h3>
<h4>(a)	Propriété intellectuelle de Netframe</h4>
<p>
Le Site, les composantes de celui-ci (contenu, images, marques, vidéos, extraits sonores, slogans, données, métadonnées, logos, graphismes, textes, programmes informatiques, etc.) sont la propriété exclusive de Netframe (et le cas échéant de ses Membres et partenaires) et font l'objet d'une protection légale à divers titres tels que notamment les droits d'auteur et droits voisins, marques, dessins et modèles, droits des producteurs de bases de données.<br />
Netframe accorde à l'Utilisateur une licence non-exclusive, strictement personnelle et non transférable l'autorisant à utiliser le Site et les Services, ainsi que les informations qu'ils contiennent pour son propre usage conformément aux présentes CGU pour la durée de son inscription en qualité de Membre et pour le monde entier. Seules les copies de ces éléments à usage privé à des fins non commerciales sont autorisées sous réserve du respect des droits de propriété intellectuelle dont il est fait mention. Toute utilisation par reproduction, modification, téléchargement, transmission ou autre procédé d'extraction et de duplication des composantes du Site par quelque procédé que ce soit (en particulier par framing, caching) est soumise à l'autorisation écrite et préalable de Netframe.<br />
Les droits d'auteur, marques et tous autres droits de propriété intellectuelle de Netframe restent la propriété exclusive de celui-ci ou, en cas de contenu fourni par des Membres et partenaires ou tous autres tiers, la propriété de ces derniers, le cas échéant. L'Utilisateur ne doit ni modifier, ni supprimer toutes mentions d'identifications concernant les droits d'auteur ou autres titres de propriété.<br />
Hormis les cas expressément mentionnés au présent Article, toute représentation totale ou partielle de ce Site par quelque personne (physique ou morale) que ce soit, sans l'autorisation expresse de Netframe, est interdite et constituerait une contrefaçon sanctionnée par les articles L.335-2 et suivants du Code de la propriété intellectuelle français.
</p>
<h4>(b)	Propriété intellectuelle du Membre</h4>
<p>
Le Membre est seul responsable de tout contenu mis en ligne sur le Site lors de l'utilisation des Services. A cet égard, il déclare être l'auteur de ce contenu – textes, images, vidéos, photographies, autres éléments – et garantit que ce contenu ne porte pas atteinte aux droits des tiers. S'il n'en est pas l'auteur, le Membre garantit avoir obtenu l'autorisation écrite préalable de l'auteur pour leur diffusion sur le Site selon les conditions décrites aux présentes CGU. Le Membre garantit également avoir obtenu la permission expresse de toutes personnes (identifiables dans les contenus) concernant la diffusion de leur image et de tout autre élément permettant leur identification.<br />
En diffusant sur le Site le contenu qu'il propose, le Membre accepte expressément que ce contenu soit reproduit et accessible aux autres Utilisateurs sur le Site ainsi que par l'intermédiaire de tous moteurs de recherche disponibles sur Internet. A cette fin, en contrepartie de l'accès aux Services dont il bénéficie, le Membre concède à titre gracieux à Netframe, dans le cadre de l'activité de Netframe ainsi qu'aux fins de diffusion du contenu aux autres Utilisateurs du Site, une licence d'utilisation non-personnelle et non-exclusive sur ce contenu pour le monde entier, pour la durée légale de protection du contenu par les droits de propriété intellectuelle (notamment le droit d'auteur). Dans ce cadre, le Membre autorise Netframe à représenter et reproduire tout ou partie du contenu qu'il fournit sur tout support, actuel ou futur, en tout format et par tout procédé connu et inconnu à ce jour, au soutien de toute opération de diffusion sur le Site et/ou au sein d'un forum de discussion ou pour numérisation, stockage, sauvegarde, transmission ou téléchargement ou autres opérations nécessaires au fonctionnement du Site et à la mise à disposition du contenu concerné. Netframe est également autorisé à adapter le contenu fourni et à représenter et reproduire ces adaptations sur tout support actuel ou futur. Cette licence comprend également la faculté de réaliser, dans le respect du droit moral du Membre, des modifications de la mise en forme de son contenu ainsi que des coupes dans le contenu, afin de respecter la charte graphique du Site, de rendre le contenu compatible avec ses performances techniques et les formats requis pour sa diffusion sur le Site et de permettre le cas échéant la reproduction du contenu sur tous autres supports de communication de Netframe.<br />
Le Membre garantit Netframe contre toutes réclamations, actions et revendications de tiers au motif que l'utilisation ou la reproduction du contenu sur le Site ou sur tous autres supports de communication constituerait une contrefaçon de droits de propriété intellectuelle ou une atteinte à tous autres droits de tiers. Dans une telle hypothèse, le Membre s'engage à indemniser Netframe de tous dommages et intérêts ainsi que de toutes indemnisations et frais de toute nature exposés par Netframe pour assurer sa défense contre toutes réclamations, actions ou revendications de tiers.
</p>
<h3>2.6.	Disponibilité du Site</h3>
<p>
Netframe se réserve la possibilité de modifier ou d'interrompre temporairement ou de façon permanente le fonctionnement de tout ou partie du Site, sans préavis, aux fins de maintenance ou autre, ce que l'Utilisateur accepte expressément.<br />
Netframe ne saurait être tenu responsable en cas de suspension ou d'interruption du fonctionnement du Site, d'indisponibilité, d'impossibilité d'accès ou de mauvaises conditions d'utilisation du Site imputables à un équipement non adapté, à des dysfonctionnements internes au fournisseur d'accès Internet de l'Utilisateur, à l'encombrement du réseau Internet, ou pour toutes autres raisons extérieures à Netframe.
</p>
<h3>2.7.	Qualité des informations diffusées sur le Site</h3>
<p>
Netframe n'est pas en mesure de garantir l'exhaustivité, l'exactitude, la véracité, la qualité, l'actualisation et la pertinence des informations figurant sur le Site, ni l'absence de modification de leur contenu par un tiers non autorisé.<br />
Le Membre reconnaît que ses demandes ultérieures de modification ou de suppression de son contenu figurant sur le Site exigent de Netframe l'accomplissement de certaines démarches techniques qui ne peuvent être réalisées instantanément. De la même manière, le Membre reconnaît que le fonctionnement d'Internet implique le maintien, pendant une période que Netframe ne maîtrise pas, d'une mémoire latente rendant accessible, notamment par l'intermédiaire de moteurs de recherche, certains contenus, informations ou données pourtant dûment effacés du présent Site.<br />
Aucune information diffusée sur ce Site ne saurait être considérée comme une incitation émanant de Netframe à vendre, acheter ou effectuer toute autre transaction. Netframe ne prétend pas davantage fournir une prestation de conseil dans un quelconque domaine. Netframe invite les Utilisateurs à rechercher le conseil d'un expert habilité avant de prendre toute décision sur le fondement d'une information diffusée sur le Site. En tout état de cause, l'usage des informations disponibles sur le Site demeure de la seule responsabilité de l'Utilisateur et les décisions qu'il serait conduit à prendre au regard de ces informations ne sauraient engager d'autre responsabilité que la sienne. Les points de vue exprimés par les différents Membres peuvent ne pas refléter l'opinion de Netframe et n'engagent que leurs auteurs.
</p>
<h3>2.8.	Hébergement des contenus diffusés par les Membres</h3>
<p>
Netframe est éditeur du présent Site, à l'exception toutefois des contenus diffusés à l'initiative de ses Membres et partenaires, pour lesquels Netframe ne joue aucun rôle actif de connaissance et de contrôle. Pour ces contenus spécifiques, intégrés aux forums de discussion ou diffusés sur le Site de quelque autre manière, Netframe agit en qualité d'hébergeur au sens de l'article 6-I-2 de la loi n°2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique (la LCEN). Le Membre demeure responsable du contenu qu'il fournit et reconnaît que Netframe n'exerce pas de contrôle a priori sur ce contenu. Le Membre est par conséquent seul responsable de tous dommages causés par tout élément de contenu diffusé à sa demande sur le Site.<br />
Netframe n'a aucune capacité d'action sur le contenu des Membres mis en ligne et sa responsabilité ne saurait par conséquent être engagée à ce titre. Netframe intervient uniquement sur le mode de mise à disposition de ces contenus : pour les nécessités de la mise en ligne, Netframe peut être amené à procéder à des modifications techniques du contenu (notamment ré-encodage, reformatage) et à son indexation afin d'en faciliter l'accès par les Utilisateurs (structuration, organisation, classification par mots-clés tels que Talents Angel, institutions - house, sports, arts, culture, innovation, idées, etc …). Netframe peut également adosser aux contenus mis en ligne des bannières publicitaires ou autres éléments promotionnels proposés par ses partenaires. En aucun cas Netframe ne détermine ni ne sélectionne les contenus fournis par les Membres.<br />
Netframe s'engage à retirer tout contenu illicite lorsque les faits litigieux lui sont dénoncés dans les formes prescrites par l'article 6-I-5 de la LCEN. Pour être efficace, toute notification de contenu illicite doit être complète, comporter l'ensemble des mentions prescrites par la LCEN et être suffisamment précise pour lui permettre notamment d'identifier le contenu concerné, de le localiser sur le Site et de le supprimer promptement ou d'en rendre l'accès impossible.<br />
L'Utilisateur est par conséquent incité à signaler à Netframe tout contenu illicite en fournissant l'ensemble des éléments suivants : (i) la date de la notification ; (ii) si le requérant est une personne physique : ses nom, prénom(s), profession, domicile, nationalité, date et lieu de naissance ; si le requérant est une personne morale : sa forme, sa dénomination, son siège social et l'organe qui la représente légalement ; (iii) une référence à la dénomination et au siège social de Netframe ; (iv) la description des faits litigieux et leur localisation précise ; (v) les motifs pour lesquels le contenu doit être retiré, comprenant la mention des dispositions légales et des justifications de faits ; et (vi) la copie de la correspondance adressée à l'auteur ou à l'éditeur des informations ou activités litigieuses demandant leur interruption, leur retrait ou leur modification, ou la justification de ce que l'auteur ou l'éditeur n'a pu être contacté.<br />
Pour rappel, Netframe n'a pas d'obligation de suppression d'un contenu qui ne paraîtrait pas manifestement illicite.
</p>
<h3>2.9.	Liens hypertextes – réseaux sociaux – référencements</h3>
<p>
Le Site présente des liens hypertextes en direction d'autres sites et propose également une interaction avec d'autres acteurs de l'Internet, notamment certains réseaux sociaux. Ces liens et ces propositions ne sauraient engager la responsabilité de Netframe en ce qui a trait au contenu de ces différents sites et des messages échangés sur les réseaux sociaux.<br />
Netframe n'est pas davantage responsable des liens hypertextes pointant vers le Site et autres référencements du présent Site réalisés par des tiers sans son autorisation préalable et expresse.
</p>
<h3>2.10.	Limitation de responsabilité</h3>
<p>
De manière générale, sous réserve que l'Utilisateur ait respecté l'intégralité des stipulations des présentes CGU et démontre qu'un dommage est la conséquence d'un manquement exclusivement imputable à Netframe au titre du présent Site, Netframe ne serait tenu que de la seule réparation des conséquences pécuniaires des dommages directs subis par l'Utilisateur.<br />
Netframe ne saurait en aucune circonstance voir sa responsabilité recherchée en cas de préjudices indirects ou imprévisibles subis par l'Utilisateur. Par préjudices indirects ou imprévisibles, il est entendu notamment toute atteinte à la vie privée de l'Utilisateur, à son image, à son intégrité, à sa dignité, à ses droits de propriété intellectuelle, toute perte de chiffre d'affaires, perte financière, inexactitude ou corruption de fichiers ou de données, préjudice commercial, perte de bénéfices, perte de clientèle, perte d'une chance, sans que cette liste soit exhaustive.
</p>
<h3>2.11.	Modification des CGU</h3>
<p>
Les CGU sont susceptibles d'être modifiées à tout moment. L'Utilisateur est par conséquent vivement invité à les consulter régulièrement.
</p>
<h3>2.12.	Loi applicable -Juridiction</h3>
<p>
Les présentes CGU sont soumises au droit français. Tout différend relatif au présent Site et/ou à l'interprétation des CGU relèvera de la compétence des juridictions françaises.
</p>
<h2>3.	POLITIQUE DE CONFIDENTIALITE</h2>
<p>
Netframe peut être amenée à collecter les données à caractère personnel de l'Utilisateur dans le cadre des Services fournis sur le Site afin (i) de traiter les demandes d'inscription aux Services et/ou de gérer la mise en place de tout autre contenu sur le Site, (ii) de connaître les pages visitées par les Utilisateurs, et (iii) sous réserve de l'autorisation expresse des Membres, permettre leur localisation afin de faciliter le rapprochement entre les Membres exerçant leurs talents par exemple dans une même région. Seules les personnes habilitées de Netframe seront destinataires de ces données.<br />
Conformément à la loi n°78-17 du 6 janvier 1978 modifiée dite « informatique et libertés », l'Utilisateur dispose d'un droit d'accès, de rectification, de suppression et d'opposition pour motifs légitimes concernant l'ensemble de ses données qu'il peut exercer en s'adressant par mail à <a href="mailto:legal@Netframe.com">legal@Netframe.com</a><br />
</p>

<p>
Dernière mise à jour : février 2017.<br />
©Tous droits réservés.
</p>
