{{- $secretName := print .Chart.Name "-netframe" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $existingSecret := $existingSecret.data | default dict -}}

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "netframe"

data:
  app-key: {{ index $existingSecret "app-key" | default "" | quote }}
