apiVersion: v1
kind: Service

metadata:
  name: {{ .Chart.Name }}-netframe
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "netframe"
    app.kubernetes.io/version: {{ required "Value appVersionNetframe is required" .Values.appVersionNetframe | quote }}

spec:
  ports:
    - port: 80
      protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/component: "netframe"
