<?php

return array(

    'FILE_SIZE_MAX' => 5242880,
    'STORAGE_PATH' => "",
    'ALONE' => false,

    'IP_ADDRESS' => env('ONLY_OFFICE_IP'),
    'PORT' => '8000',

    'DOC_SERV_VIEWD' => [ '.pdf', '.djvu', '.xps' ],
    'DOC_SERV_EDITED' => [ '.docx', '.xlsx', '.csv', '.pptx', '.txt' ],
    'DOC_SERV_CONVERT' => [
        '.docm',
        '.doc',
        '.dotx',
        '.dotm',
        '.dot',
        '.odt',
        '.fodt',
        '.ott',
        '.xlsm',
        '.xls',
        '.xltx',
        '.xltm',
        '.xlt',
        '.ods',
        '.fods',
        '.ots',
        '.pptm',
        '.ppt',
        '.ppsx',
        '.ppsm',
        '.pps',
        '.potx',
        '.potm',
        '.pot',
        '.odp',
        '.fodp',
        '.otp',
        '.rtf',
        '.mht',
        '.html',
        '.htm',
        '.epub',
        '.pdf'
    ],

    'DOC_SERV_TIMEOUT' => "120000",

    'DOC_SERV_CONVERTER_URL' => "/ConvertService.ashx",
    'DOC_SERV_API_URL' => "/web-apps/apps/api/documents/api.js",

    'DOC_SERV_PRELOADER_URL' => "/web-apps/apps/api/documents/cache-scripts.html",

    'MOBILE_REGEX' => implode('|', [
        'android',
        'avantgo',
        'playbook',
        'blackberry',
        'blazer',
        'compal',
        'elaine',
        'fennec',
        'hiptop',
        'iemobile',
        'ip(hone|od|ad)',
        'iris',
        'kindle',
        'lge ',
        'maemo',
        'midp',
        'mmp',
        'opera m(ob|in)i',
        'palm( os)?',
        'phone',
        'p(ixi|re)\\/',
        'plucker',
        'pocket',
        'psp',
        'symbian',
        'treo',
        'up\\.(browser|link)',
        'vodafone',
        'wap',
        'windows (ce|phone)',
        'xda',
        'xiino'
    ]),


    'ExtsSpreadsheet' => array(".xls", ".xlsx", ".xlsm",
                                    ".xlt", ".xltx", ".xltm",
                                    ".ods", ".fods", ".ots", ".csv"),

    'ExtsPresentation' => array(".pps", ".ppsx", ".ppsm",
                                     ".ppt", ".pptx", ".pptm",
                                     ".pot", ".potx", ".potm",
                                     ".odp", ".fodp", ".otp"),

    'ExtsDocument' => array(".doc", ".docx", ".docm",
                                 ".dot", ".dotx", ".dotm",
                                 ".odt", ".fodt", ".ott", ".rtf", ".txt",
                                 ".html", ".htm", ".mht",
                                 ".pdf", ".djvu", ".fb2", ".epub", ".xps"),
);
