apiVersion: v1
kind: Service
metadata:
  name: netframe-netframe
  namespace: netframe-local
  labels:
    app: netframe
    tier: netframe
    environment: local
spec:
  ports:
    - port: 80
      protocol: TCP
  clusterIP: None
  selector:
    app: netframe
    tier: netframe
    environment: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netframe-netframe
  namespace: netframe-local
  labels:
    app: netframe
    tier: netframe
    environment: local
spec:
  selector:
    matchLabels:
      app: netframe
      tier: netframe
      environment: local
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      namespace: netframe-local
      labels:
        app: netframe
        tier: netframe
        environment: local
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 33 # this is www-data GID in the Docker PHP image
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: netframe-netframe-init-uploads
          image: busybox:1.33.0
          command:
            - "/bin/sh"
            - "-c"
            - "mkdir -m 774 -p /var/www/html/storage/uploads/documents/pdf /var/www/html/storage/uploads/documents/preview"
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/storage/uploads
      containers:
        - name: netframe-netframe
          image: kz91436x.gra7.container-registry.ovh.net/netframe/netframe:0.0.0
          workingDir: /var/www/html
          ports:
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: netframe
                  key: env
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: netframe
                  key: app-key
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: netframe
                  key: url
            - name: APP_BASE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: netframe
                  key: base-domain
            - name: APP_BASE_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: netframe
                  key: base-protocol
            - name: SESSION_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: netframe
                  key: session-domain
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: cache
                  key: host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: cache
                  key: port
            - name: SEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: search
                  key: uri
            - name: MAIL_DRIVER
              value: "log"
            - name: LOG_MAILS_DATA
              value: "1"
            - name: PROXY_FILE_SENDING_HEADER
              value: "X-Accel-Redirect"
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: uploads
              mountPath: /var/www/html/storage/uploads
          startupProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "stat -c %U /var/www/html/public/index.php | grep -q www-data"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "cp -r /app/* /var/www/html/ && chown -R www-data:www-data /var/www/html/storage/ /var/www/html/public/"
        - name: http
          image: "nginx:1.18.0"
          ports:
            - containerPort: 80
          volumeMounts:
            # Nginx configuration
            - name: netframe-http
              mountPath: /etc/nginx/conf.d
            # Netframe application
            - name: app
              mountPath: /var/www/html
            # Uploads for x-send-file
            - name: uploads
              mountPath: /var/www/html/storage/uploads
      volumes:
        - name: uploads
          hostPath:
            path: /data/netframe/uploads
            type: DirectoryOrCreate
        - name: app
          emptyDir: {}
        - name: http
          configMap:
            name: http
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: netframe-netframe-task-thumbnails
  namespace: netframe-local
  labels:
    app: netframe
    tier: thumbnails
    environment: local
spec:
  schedule: "*/2 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: netframe-local
          labels:
            app: netframe
            tier: thumbnails
            environment: local
        spec:
          restartPolicy: Never
          containers:
            - name: netframe-netframe-task-thumbnails
              image: kz91436x.gra7.container-registry.ovh.net/netframe/netframe:0.0.0
              args:
                - /usr/local/bin/php
                - artisan
                - documents:thumbnail:generate
              env:
                - name: APP_ENV
                  valueFrom:
                    configMapKeyRef:
                      name: netframe
                      key: env
                - name: APP_KEY
                  valueFrom:
                    secretKeyRef:
                      name: netframe
                      key: app-key
                - name: APP_URL
                  valueFrom:
                    configMapKeyRef:
                      name: netframe
                      key: url
                - name: APP_BASE_DOMAIN
                  valueFrom:
                    configMapKeyRef:
                      name: netframe
                      key: base-domain
                - name: APP_BASE_PROTOCOL
                  valueFrom:
                    configMapKeyRef:
                      name: netframe
                      key: base-protocol
                - name: SESSION_DOMAIN
                  valueFrom:
                    configMapKeyRef:
                      name: netframe
                      key: session-domain
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: database
                      key: host
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: database
                      key: database
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: database
                      key: user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database
                      key: password
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: cache
                      key: host
                - name: REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: cache
                      key: port
                - name: SEARCH_HOSTS
                  valueFrom:
                    configMapKeyRef:
                      name: search
                      key: uri
                - name: MAIL_DRIVER
                  value: "log"
                - name: LOG_MAILS_DATA
                  value: "1"
              volumeMounts:
                - name: uploads
                  mountPath: /var/www/html/storage/uploads
          volumes:
            - name: uploads
              hostPath:
                path: /data/netframe/uploads
                type: DirectoryOrCreate
