apiVersion: v1
kind: Service

metadata:
  name: {{ .Chart.Name }}-onlyoffice
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "onlyoffice"
    app.kubernetes.io/version: "5.5.3"

spec:
  ports:
    - port: 80
      protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/component: "onlyoffice"
