{{- if eq .Values.appProtocol "https" -}}
{{- $secretName := print .Chart.Name "-acme" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $existingSecret := $existingSecret.data | default dict -}}

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "acme"

data:
  ACME_EMAIL: {{ index $existingSecret "ACME_EMAIL" | default (required "Value acmeEmail is required" .Values.acmeEmail | b64enc) | quote }}
  OVH_ENDPOINT: {{ index $existingSecret "OVH_ENDPOINT" | default "" | quote }}
  OVH_APPLICATION_KEY: {{ index $existingSecret "OVH_APPLICATION_KEY" | default "" | quote }}
  OVH_APPLICATION_SECRET: {{ index $existingSecret "OVH_APPLICATION_SECRET" | default "" | quote }}
  OVH_CONSUMER_KEY: {{ index $existingSecret "OVH_CONSUMER_KEY" | default "" | quote }}
  # @WARNING ACME_* informations, excluding ACME_EMAIL, are automatically generated,
  # you should never change them manually
  ACME_REGISTRATION_DATA: {{ index $existingSecret "ACME_REGISTRATION_DATA" | default "" | quote }}
  ACME_USER_PRIVATE_KEY: {{ index $existingSecret "ACME_USER_PRIVATE_KEY" | default "" | quote }}
{{- end -}}
