{{- $secretName := print .Chart.Name "-external" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $existingSecret := $existingSecret.data | default dict -}}

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "external"

data:
  database-host: {{ index $existingSecret "database-host" | default "" | quote }}
  database-user: {{ index $existingSecret "database-user" | default "" | quote }}
  database-password: {{ index $existingSecret "database-password" | default "" | quote }}
  database-database: {{ index $existingSecret "database-database" | default "" | quote }}
  cache-host: {{ index $existingSecret "cache-host" | default "" | quote }}
  cache-port: {{ index $existingSecret "cache-port" | default "" | quote }}
  cache-password: {{ index $existingSecret "cache-password" | default "" | quote }}
  search-uri: {{ index $existingSecret "search-uri" | default "" | quote }}
  mail-host: {{ index $existingSecret "mail-host" | default "" | quote }}
  mail-port: {{ index $existingSecret "mail-port" | default "" | quote }}
  mail-username: {{ index $existingSecret "mail-username" | default "" | quote }}
  mail-password: {{ index $existingSecret "mail-password" | default "" | quote }}
