{{- $secretName := print .Chart.Name "-registry" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $existingSecret := $existingSecret.data | default dict -}}

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson

metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "registry"

  annotations:
    helm.sh/resource-policy: "keep"

data:
  ".dockerconfigjson": {{ index $existingSecret ".dockerconfigjson" | default "eyJhdXRocyI6e319" | quote }}
