apiVersion: v1
kind: Service

metadata:
  name: {{ .Chart.Name }}-collab
  namespace: {{ .Release.Namespace | quote }}

  labels: {{ include (print .Template.BasePath "/_labels-default.yaml") . | nindent 4 }}
    app.kubernetes.io/component: "collab"
    app.kubernetes.io/version: {{ required "Value appVersionCollab is required" .Values.appVersionCollab | quote }}

spec:
  ports:
    - port: 3000
      protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/component: "collab"
