name: Clean workflows

on:
  schedule:
    - cron: '0 12,20 * * 1-5'

jobs:
  clean-workflows:
    name: Clean branch workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install -r .github/workflows/requirements.txt
      - name: Clean
        run: python .github/workflows/clean-workflows.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
